package com.simple.coloniahlvs.controllers;

import com.simple.coloniahlvs.domain.dto.GeneralResponse;
import lombok.extern.slf4j.Slf4j;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

@RestController
@RequestMapping("/api/entrance")
@Slf4j
@CrossOrigin
public class EntranceController {

    @GetMapping("/resident/qr")
    public ResponseEntity<GeneralResponse> getResidentQR(){
        return GeneralResponse.getResponse("QR generated by table user (only works for resident)");
    }

    @GetMapping("/visitor/qr")
    public ResponseEntity<GeneralResponse> getQR(){
        return GeneralResponse.getResponse("QR generated by permission");
    }

    @GetMapping("/house-history")
    public ResponseEntity<GeneralResponse> getHouseHistory(){
        return GeneralResponse.getResponse("My House history");
    }

    @GetMapping("/history")
    public ResponseEntity<GeneralResponse> getHistory(){
        return GeneralResponse.getResponse("All time history");
    }

    @GetMapping("/recent")
    public ResponseEntity<GeneralResponse> getRecent(){
        return GeneralResponse.getResponse("week history");
    }

    @PostMapping("/validate-entrance")
    public ResponseEntity<GeneralResponse> validateEntrance(@RequestBody String info) {
        return GeneralResponse.getResponse("Entry validated!");
    }

    @PostMapping("/manual-entry")
    public ResponseEntity<GeneralResponse> manualEntry(@RequestBody String info) {
        return GeneralResponse.getResponse("Manual entry validated!");
    }

}
